### ISSUE TITLE
A/B型判別方法、変更のお願い

### ISSUE THREAD

**Issue by LawAI** [haik-law/convert_to_text#2]
お疲れ様です！

AB型判別を現在ファイル名でやって頂いていると思うのですが、
ユーザーが使用する際、
ファイル名にA型と記載されるとは限りません。

最初からお伝え出来ず恐縮なのですが、
例えば、
（タイトル）
第〇条
の「タイトルと条番」の位置関係などを使って、
判別をお願い出来ますでしょうか？？

**Comment by michio-kaigo** [comment]
”第”ではじまる文の一行前のものに着目して機能実装しました。
